# ETC

Miscellaneous Things

In [ ]:
"""
Change String Encoding
"""
#!/usr/bin/env python
# -*- coding: utf-8 -*-

write at Header of the Source

## Get Id of variable

In [1]:
x = 1004
print(x, id(x))

1004 2802154357168

## Set int to binary, octal, decimal, exadecimal.

In [2]:
binary_number = 0b10
octal_number = 0o10
decimal_number = 10
hexadecimal_number = 0x10
print(binary_number, octal_number, decimal_number, hexadecimal_number)

2 8 10 16

In [2]:
from bigsdatachatbot.utils import stock_datetime as sdt
from bigsdatachatbot import all_stocks_updater as as_updater
from datetime import datetime

import FinanceDataReader as fdr
import pandas as pd

_holiday = sdt.get_stock_holiday('C:/Users/student/Downloads')
# 모든 종목 코드와 종목명 수집
cn = as_updater.collect_all_stocks_cn()
# 오늘 날짜, 개장일 기준으로 60일 리스트 수집
start = sdt.get_n_open_date(today=datetime.now(), n=60, holiday=_holiday)
# 가격을 수집할 시작날짜, 끝 날짜 저장
start, end = min(start).strftime("%Y-%m-%d"), max(start).strftime("%Y-%m-%d")
all_stocks_price, passed_codes = [], []

In [4]:
for code in tqdm(cn['code'].tolist()):
    try:
        price_temp = fdr.DataReader(code[1:] if code[0]=='a' else code, start, end)
        price_temp = price_temp[['Date', 'Close']].copy()
        price_temp.loc[:, 'code'] = code
        price_temp.index = range(price_temp.shape[0])
        all_stocks_price.append(price_temp)
    except:
        passed_codes.append(code)
all_stocks_price = pd.concat(all_stocks_price)
all_stocks_price.columns = list(map(lambda x: x.lower(), all_stocks_price.columns))
# save AllStocksPrice

'./data/krx_holiday_2019.xls'

In [6]:
code = 'a001040'
price_temp = fdr.DataReader(code[1:] if code[0]=='a' else code, start, end)

In [11]:
pd.concat(all_stocks_price)

         Date   Close     code
0  2018-10-05  124943  a001040
1  2018-10-08  124471  a001040
2  2018-10-10  118814  a001040
3  2018-10-11  110798  a001040
4  2018-10-12  110798  a001040
5  2018-10-15  108441  a001040
6  2018-10-16  108441  a001040
7  2018-10-17  112684  a001040
8  2018-10-18  110798  a001040
9  2018-10-19  113156  a001040
10 2018-10-22  114099  a001040
11 2018-10-23  109856  a001040
12 2018-10-24  111270  a001040
13 2018-10-25  108441  a001040
14 2018-10-26  104669  a001040
15 2018-10-29  102312  a001040
16 2018-10-30  101369  a001040
17 2018-10-31  102783  a001040
18 2018-11-01  103726  a001040
19 2018-11-02  106555  a001040
20 2018-11-05  103726  a001040
21 2018-11-06  106084  a001040
22 2018-11-07  105612  a001040
23 2018-11-08  104198  a001040
24 2018-11-09  112213  a001040
25 2018-11-12  114099  a001040
26 2018-11-13  113627  a001040
27 2018-11-14  112684  a001040
28 2018-11-15  117871  a001040
29 2018-11-16  117871  a001040
..        ...     ...      ...
30 2018-11-19  122114  a001040
31 2018-11-20  123529  a001040
32 2018-11-21  124000  a001040
33 2018-11-22  120700  a001040
34 2018-11-23  119757  a001040
35 2018-11-26  120700  a001040
36 2018-11-27  121171  a001040
37 2018-11-28  124471  a001040
38 2018-11-29  122586  a001040
39 2018-11-30  123057  a001040
40 2018-12-03  124943  a001040
41 2018-12-04  121643  a001040
42 2018-12-05  121643  a001040
43 2018-12-06  121171  a001040
44 2018-12-07  119757  a001040
45 2018-12-10  120228  a001040
46 2018-12-11  119285  a001040
47 2018-12-12  124000  a001040
48 2018-12-13  123057  a001040
49 2018-12-14  121643  a001040
50 2018-12-17  122114  a001040
51 2018-12-18  122586  a001040
52 2018-12-19  124471  a001040
53 2018-12-20  122114  a001040
54 2018-12-21  128715  a001040
55 2018-12-24  126357  a001040
56 2018-12-26  124000  a001040
57 2018-12-27  120500  a001040
58 2018-12-28  121500  a001040
59 2019-01-02  116000  a001040

[120 rows x 3 columns]